export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  ARCHIVED = 'ARCHIVED',
}

export enum RoleTitle {
  MANAGER = 'MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  ACCOUNTANT = 'ACCOUNTANT',
  INSTRUCTOR = 'INSTRUCTOR',
  STUDENT = 'STUDENT',
}

export enum StudentStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  IN_TRAINING = 'IN_TRAINING',
  CERTIFICATE_SEEKER = 'CERTIFICATE_SEEKER',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum InstructorType {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
  BOTH = 'BOTH',
}

export enum VehicleType {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
}

export enum VehicleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum VehicleSource {
  SCHOOL_CAR = 'SCHOOL_CAR',
  STUDENT_CAR = 'STUDENT_CAR',
}

export enum BookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  BOOKED = 'BOOKED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentStatus {
  PENDING_DEPOSIT = 'PENDING_DEPOSIT',
  DEPOSIT_PAID = 'DEPOSIT_PAID',
  FULLY_PAID = 'FULLY_PAID',
  DEPOSIT_NON_REFUNDABLE = 'DEPOSIT_NON_REFUNDABLE',
  DEPOSIT_AVAILABLE_FOR_REBOOKING = 'DEPOSIT_AVAILABLE_FOR_REBOOKING',
  DEPOSIT_USED_IN_REBOOKING = 'DEPOSIT_USED_IN_REBOOKING',
}

export enum TrainingType {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
}

export enum VehicleUnavailableReasonType {
  MAINTENANCE = 'MAINTENANCE',
  UNAVAILABLE = 'UNAVAILABLE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}

export enum CancellationParty {
  STUDENT = 'STUDENT',
  VEHICLE = 'VEHICLE',
  INSTRUCTOR = 'INSTRUCTOR',
  SCHOOL = 'SCHOOL',
}

export enum DayOfWeek {
  SAT = 'SAT',
  SUN = 'SUN',
  MON = 'MON',
  TUE = 'TUE',
  WED = 'WED',
  THU = 'THU',
  FRI = 'FRI',
}

export enum ChargeReason {
  LESSON = 'LESSON',
  LESSON_DEPOSIT = 'LESSON_DEPOSIT',
  LESSON_REMAINDER = 'LESSON_REMAINDER',
  CERTIFICATE_FEE = 'CERTIFICATE_FEE',
  TRANSPORT_LECTURE = 'TRANSPORT_LECTURE',
  TRANSPORT_EXAM = 'TRANSPORT_EXAM',
  REEXAM_THEORY = 'REEXAM_THEORY',
  REEXAM_PRACTICAL = 'REEXAM_PRACTICAL',
  OTHER = 'OTHER',
}

export enum ChargeStatus {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  SHAM_CASH = 'SHAM_CASH',
}

export enum ExpenseCategory {
  VEHICLE = 'VEHICLE',
  INSTRUCTOR = 'INSTRUCTOR',
  EMPLOYEE = 'EMPLOYEE',
  GENERAL = 'GENERAL',
}

export enum ExpenseStatus {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
}

export enum VehicleExpenseReason {
  MAINTENANCE = 'MAINTENANCE',
  GAS = 'GAS',
  INSURANCE = 'INSURANCE',
  OTHER = 'OTHER',
}

export enum EmployeeExpenseType {
  SALARY = 'SALARY',
  BONUS = 'BONUS',
  OTHER = 'OTHER',
}

export enum GeneralExpenseType {
  WATER = 'WATER',
  ELECTRICITY = 'ELECTRICITY',
  INTERNET = 'INTERNET',
  KITCHEN = 'KITCHEN',
  SUPPLIES = 'SUPPLIES',
  OTHER = 'OTHER',
}

export enum InstructorPriceType {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum CertificateCategory {
  B = 'B',
  B1 = 'B1',
  C = 'C',
  D = 'D',
}

export enum CertificateRequestStatus {
  WAITING_FOR_SERVICE_FEE = 'WAITING_FOR_SERVICE_FEE',
  WAITING_FOR_TRAINING_SCHEDULE = 'WAITING_FOR_TRAINING_SCHEDULE',
  IN_GOVERNMENT_TRAINING = 'IN_GOVERNMENT_TRAINING',
  WAITING_FOR_PRACTICAL_EXAM = 'WAITING_FOR_PRACTICAL_EXAM',
  WAITING_FOR_THEORETICAL_EXAM = 'WAITING_FOR_THEORETICAL_EXAM',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ExamType {
  THEORY = 'THEORY',
  PRACTICAL = 'PRACTICAL',
}

export enum ExamResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  ABSENT = 'ABSENT',
}

export enum TripType {
  LECTURE = 'LECTURE',
  EXAM = 'EXAM',
}

export enum TripStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum RegistrationStatus {
  REGISTERED = 'REGISTERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AttendanceStatus {
  PENDING = 'PENDING',
  ATTENDED = 'ATTENDED',
  ABSENT = 'ABSENT',
}

export enum SettingValueType {
  NUMBER = 'NUMBER',
  STRING = 'STRING',
  TIME = 'TIME',
  PERCENT = 'PERCENT',
  BOOLEAN = 'BOOLEAN',
}

export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_EXPIRED = 'BOOKING_EXPIRED',
  PAYMENT_ACCEPTED = 'PAYMENT_ACCEPTED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  CERTIFICATE_STATUS_CHANGED = 'CERTIFICATE_STATUS_CHANGED',
  INSTRUCTOR_SCHEDULE = 'INSTRUCTOR_SCHEDULE',
  GENERAL = 'GENERAL',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  SMS = 'SMS',
  PUSH = 'PUSH',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  READ = 'READ',
}

export enum OtpPurpose {
  STUDENT_LOGIN = 'STUDENT_LOGIN',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
}
